### ISSUE TITLE
Test fails out-of-the-box

### ISSUE THREAD

**Issue by egeland** [miguelgrinberg/api-pycon2014#1]
I followed the instructions (copy/paste) and still get this test failing:

```
FAIL: test_pagination (tests.test_api.TestAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/python/api-pycon2014/tests/test_api.py", line 359, in test_pagination
    self.assertTrue(one_url in json['urls'])
AssertionError: False is not true
```

**Comment by miguelgrinberg** [comment]
You may want to print `json['urls']` and `one_url` to see where the disconnect is. I just reran the tests on Python 3.4 and get all passing. What Python version are you using?

**Comment by egeland** [comment]
Thanks for responding.
I'm using Python 3.3.2+ on Ubuntu 13.10

If I find some time, I'll try to figure it out..

**Comment by Siecje** [comment]
When I run them I get 

``` python
Traceback (most recent call last):
  File "/home/siecje/Desktop/api-pycon2014/venv/lib/python3.4/site-packages/werkzeug/utils.py", line 406, in import_string
    return __import__(import_name)
ImportError: No module named 'development'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 43, in <module>
    manager.run()
  File "/home/siecje/Desktop/api-pycon2014/venv/lib/python3.4/site-packages/flask_script/__init__.py", line 423, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/siecje/Desktop/api-pycon2014/venv/lib/python3.4/site-packages/flask_script/__init__.py", line 398, in handle
    app = self.create_app(**app_config)
  File "/home/siecje/Desktop/api-pycon2014/venv/lib/python3.4/site-packages/flask_script/__init__.py", line 140, in create_app
    return self.app(**kwargs)
  File "/home/siecje/Desktop/api-pycon2014/api/app.py", line 10, in create_app
    'config')
  File "/home/siecje/Desktop/api-pycon2014/venv/lib/python3.4/site-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/home/siecje/Desktop/api-pycon2014/venv/lib/python3.4/site-packages/werkzeug/utils.py", line 424, in import_string
    sys.exc_info()[2])
  File "/home/siecje/Desktop/api-pycon2014/venv/lib/python3.4/site-packages/werkzeug/_compat.py", line 133, in reraise
    raise value.with_traceback(tb)
  File "/home/siecje/Desktop/api-pycon2014/venv/lib/python3.4/site-packages/werkzeug/utils.py", line 406, in import_string
    return __import__(import_name)
werkzeug.utils.ImportStringError: import_string() failed for 'development'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'development' not found.

Original exception:

ImportError: No module named 'development'
```

**Comment by miguelgrinberg** [comment]
This seems more a setup problem than anything else. Here are the steps I followed:
- cloned the repository and then `cd` into it.
- `python3.4 -m venv venv` to create a virtual environment
- `source venv/bin/activate` to activate it
- `pip install -r requirements.txt`
- `./manage.py test`

Does this match what you are doing on your side?

**Comment by Siecje** [comment]
`$ python3.4 -m venv venv`
doesn't seem to work for me. It doesn't create /bin/activate
I use 
`$ virtualenv -p /usr/bin/python3.4 venv`

Full terminal here https://dpaste.de/sLwH

**Comment by miguelgrinberg** [comment]
This issue will be automatically closed due to being inactive for more than six months. Seeing that I haven't responded to your last comment, it is quite possible that I have dropped the ball on this issue and I apologize about that. If that is the case, do not take the closing of the issue personally as it is an automated process doing it, just reopen it and I'll get back to you.
