### ISSUE TITLE
Testing with TestClient

### ISSUE THREAD

**Issue by Siecje** [miguelgrinberg/api-pycon2014#2]
When testing with TestClient raised exceptions are not being caught.
If you have 

```
Model.query.get_or_404(id)
```

and a 404 is raised there will be an error with a traceback

I was checking to see if you already solved this problem in your newer repos, but since I can't run the tests for this repo I have have created a branch for your flasky repo and added test_client.py as test_client2.py

https://github.com/Siecje/flasky/tree/testing_404

When you run the tests, the test with TestClient fails, but the test with `self.app.test_client()` and `get_api_headers()` does not.

Test traceback

``` python
Traceback (most recent call last):
  File "/home/siecje/Desktop/flasky/tests/test_api.py", line 57, in test_user_does_not_exist_404
    '/api/v1.0/users/%d' % 900)
  File "/home/siecje/Desktop/flasky/tests/test_client2.py", line 39, in get
    return self.send(url, 'GET', headers=headers)
  File "/home/siecje/Desktop/flasky/tests/test_client2.py", line 33, in send
    rv = self.app.dispatch_request()
  File "/home/siecje/Desktop/flasky/venv/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/siecje/Desktop/flasky/app/api_1_0/users.py", line 8, in get_user
    user = User.query.get_or_404(id)
  File "/home/siecje/Desktop/flasky/venv/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 384, in get_or_404
    abort(404)
  File "/home/siecje/Desktop/flasky/venv/local/lib/python2.7/site-packages/werkzeug/exceptions.py", line 576, in __call__
    raise self.mapping[code](*args, **kwargs)
NotFound: 404: Not Found

```

**Comment by miguelgrinberg** [comment]
The way I would test a 404 is by using `self.assertRaises()` directly in the test, you do not need the testing framework to catch them.

**Comment by Siecje** [comment]
Notice the differences in the tests

``` python
    def test_user_does_not_exist(self):
        response = self.client.get(
            '/api/v1.0/users/%d' % 900,
            headers=self.get_api_headers(self.user.email, 'admin'))
        self.assertEqual(response.status_code, 404)

    def test_user_does_not_exist_404(self):
        response = self.client2.get(
            '/api/v1.0/users/%d' % 900)
        self.assertEqual(response.status_code, 404)
```

So it is better to do (I can't get it to pass)

``` python
    def test_user_does_not_exist_404(self):
        from werkzeug.exceptions import NotFound
        self.assertRaises(NotFound, response = self.client2.get(
            '/api/v1.0/users/%d' % 900))
```

That is fine for a 404 page when you are not testing that the page contains a certain error message for example you have 

``` python
@staticmethod
def from_json(json_post):
    body = json_post.get('body')
    if body is None or body == '':
        raise ValidationError('post does not have a body')
    return Post(body=body)
```

Since exceptions are not handled properly you can't test that the page contians the correct text.

**Comment by miguelgrinberg** [comment]
Hmm. Okay, I guess you are right, routing the exceptions through the error handlers enables you to test that you get the correct error page.

**Comment by Siecje** [comment]
Thanks to @mattupstate for the TestClient code I was able to replace it with 

``` python
    self.client = self.app.test_client()
    self.client.auth = 'Basic ' + b64encode(
            (self.user.email + ':' + 'admin').encode('utf-8')).decode('utf-8')
    # ...
    response = self.client.jget('/api/v1.0/posts')
```

``` python
from flask import Response, json
from flask.testing import FlaskClient


_missing = object()


class TestResponse(Response):  # pragma: no cover

    @property
    def jdata(self):
        rv = getattr(self, '_cached_jdata', _missing)
        if rv is not _missing:
            return rv
        try:
            self._cached_jdata = json.loads(self.data)
        except ValueError:
            raise Exception('Invalid JSON response')
        return self._cached_jdata


class TestClient(FlaskClient):

    default_json_body_content_type = 'application/json'
    default_json_accept_content_type = 'application/json'

    def _default_json_kwargs(self, kwargs):
        kwargs.setdefault('headers', {})
        kwargs['headers'].setdefault('Accept', self.default_json_accept_content_type)
        kwargs['headers'].setdefault('Authorization', self.auth)
        kwargs.setdefault('content_type', self.default_json_body_content_type)
        if 'data' in kwargs:
            kwargs['data'] = json.dumps(kwargs['data'])
        return kwargs

    def jget(self, *args, **kwargs):
        return self.get(*args, **self._default_json_kwargs(kwargs))

    def jpost(self, *args, **kwargs):
        return self.post(*args, **self._default_json_kwargs(kwargs))

    def jput(self, *args, **kwargs):
        return self.put(*args, **self._default_json_kwargs(kwargs))

    def jpatch(self, *args, **kwargs):
        return self.patch(*args, **self._default_json_kwargs(kwargs))

    def jdelete(self, *args, **kwargs):
        return self.delete(*args, **self._default_json_kwargs(kwargs))
```
